@startuml
title
    ** src ** (Root folder)
    |_ ** main **
      |_ Calculator
      |_ Equation
    |_ ** test **
      |_ CalculatorTest
      |_ EquationTest
    |_ ** docs **
      |_ uml
      |_ png
end title
@enduml
